# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Iterable, Optional
from typing_extensions import TypedDict

from .._types import SequenceNotStr

__all__ = ["ClassificationCreateParams"]


class ClassificationCreateParams(TypedDict, total=False):
    examples: Optional[Iterable[SequenceNotStr[str]]]
    """A list of examples with labels, in the following format:

    `[["The movie is so interesting.", "Positive"], ["It is quite boring.", "Negative"], ...]`

    All the label strings will be normalized to be capitalized.

    You should specify either `examples` or `file`, but not both.
    """

    expand: Optional[Iterable[object]]
    """
    If an object name is in the list, we provide the full information of the object;
    otherwise, we only provide the object ID. Currently we support `completion` and
    `file` objects for expansion.
    """

    file: Optional[str]
    """The ID of the uploaded file that contains training examples.

    See [upload file](/docs/api-reference/files/upload) for how to upload a file of
    the desired format and purpose.

    You should specify either `examples` or `file`, but not both.
    """

    labels: Optional[SequenceNotStr[str]]
    """The set of categories being classified.

    If not specified, candidate labels will be automatically collected from the
    examples you provide. All the label strings will be normalized to be
    capitalized.
    """

    logit_bias: Optional[object]
    """Modify the likelihood of specified tokens appearing in the completion.

    Accepts a json object that maps tokens (specified by their token ID in the GPT
    tokenizer) to an associated bias value from -100 to 100. You can use this
    [tokenizer tool](/tokenizer?view=bpe) (which works for both GPT-2 and GPT-3) to
    convert text to token IDs. Mathematically, the bias is added to the logits
    generated by the model prior to sampling. The exact effect will vary per model,
    but values between -1 and 1 should decrease or increase likelihood of selection;
    values like -100 or 100 should result in a ban or exclusive selection of the
    relevant token.

    As an example, you can pass `{"50256": -100}` to prevent the <|endoftext|> token
    from being generated.
    """

    logprobs: Optional[int]
    """
    Include the log probabilities on the `logprobs` most likely tokens, as well the
    chosen tokens. For example, if `logprobs` is 5, the API will return a list of
    the 5 most likely tokens. The API will always return the `logprob` of the
    sampled token, so there may be up to `logprobs+1` elements in the response.

    The maximum value for `logprobs` is 5. If you need more than this, please
    contact support@khulnasoft.com and describe your use case.

    When `logprobs` is set, `completion` will be automatically added into `expand`
    to get the logprobs.
    """

    max_examples: Optional[int]
    """
    The maximum number of examples to be ranked by
    [Search](/docs/api-reference/searches/create) when using `file`. Setting it to a
    higher value leads to improved accuracy but with increased latency and cost.
    """

    model: str
    """ID of the engine to use for completion."""

    query: str
    """Query to be classified."""

    return_metadata: Optional[bool]
    """A special boolean flag for showing metadata.

    If set to `true`, each document entry in the returned JSON will contain a
    "metadata" field.

    This flag only takes effect when `file` is set.
    """

    return_prompt: Optional[bool]
    """
    If set to `true`, the returned JSON will include a "prompt" field containing the
    final prompt that was used to request a completion. This is mainly useful for
    debugging purposes.
    """

    search_model: Optional[str]
    """ID of the engine to use for [Search](/docs/api-reference/searches/create)."""

    temperature: Optional[float]
    """What sampling `temperature` to use.

    Higher values mean the model will take more risks. Try 0.9 for more creative
    applications, and 0 (argmax sampling) for ones with a well-defined answer.
    """
